// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbd0qVkkfe5THMl0TGollMNYsJtnGrJYM',
    appId: '1:1050768406329:web:a0e8dc6e4c6c6386b11ae8',
    messagingSenderId: '1050768406329',
    projectId: 'chamcongapp-bd5ce',
    authDomain: 'chamcongapp-bd5ce.firebaseapp.com',
    storageBucket: 'chamcongapp-bd5ce.firebasestorage.app',
    measurementId: 'G-NC31TTKTRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbd0qVkkfe5THMl0TGollMNYsJtnGrJYM',
    appId: '1:1050768406329:android:a0e8dc6e4c6c6386b11ae8',
    messagingSenderId: '1050768406329',
    projectId: 'chamcongapp-bd5ce',
    storageBucket: 'chamcongapp-bd5ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbd0qVkkfe5THMl0TGollMNYsJtnGrJYM',
    appId: '1:1050768406329:ios:a0e8dc6e4c6c6386b11ae8',
    messagingSenderId: '1050768406329',
    projectId: 'chamcongapp-bd5ce',
    storageBucket: 'chamcongapp-bd5ce.firebasestorage.app',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbd0qVkkfe5THMl0TGollMNYsJtnGrJYM',
    appId: '1:1050768406329:ios:a0e8dc6e4c6c6386b11ae8',
    messagingSenderId: '1050768406329',
    projectId: 'chamcongapp-bd5ce',
    storageBucket: 'chamcongapp-bd5ce.firebasestorage.app',
    iosBundleId: 'com.example.attendanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbd0qVkkfe5THMl0TGollMNYsJtnGrJYM',
    appId: '1:1050768406329:web:a0e8dc6e4c6c6386b11ae8',
    messagingSenderId: '1050768406329',
    projectId: 'chamcongapp-bd5ce',
    authDomain: 'chamcongapp-bd5ce.firebaseapp.com',
    storageBucket: 'chamcongapp-bd5ce.firebasestorage.app',
    measurementId: 'G-NC31TTKTRB',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDbd0qVkkfe5THMl0TGollMNYsJtnGrJYM',
    appId: '1:1050768406329:web:a0e8dc6e4c6c6386b11ae8',
    messagingSenderId: '1050768406329',
    projectId: 'chamcongapp-bd5ce',
    authDomain: 'chamcongapp-bd5ce.firebaseapp.com',
    storageBucket: 'chamcongapp-bd5ce.firebasestorage.app',
    measurementId: 'G-NC31TTKTRB',
  );
}
